# Generated by Django 5.2.5 on 2025-08-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_exam_examitem_examchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='examitem',
            name='mix_choices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
