# Generated by Django 5.2.5 on 2025-08-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_exam_end_time_exam_is_active_exam_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
